### ISSUE TITLE
The infrastructure/DEPLOYMENT.md instructions do not work

### ISSUE THREAD

**Issue by charalamm** [developmentseed/eoAPI#100]
#### Problem description

The instructions in `infrastructure/DEPLOYMENT.md` did not work and the `CDK_EOAPI_DB_PGSTAC_VERSION` is outdated.

Specifically:
* The command `CDK_EOAPI_STAGE=staging CDK_EOAPI_DB_PGSTAC_VERSION=0.7.1 npm --prefix infrastructure/aws run cdk -- synth` returns `AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.`. I run `npm --prefix infrastructure/aws run cdk bootstrap` and after re-run the commands but nothing changed.
* The command `CDK_EOAPI_STAGE=staging CDK_EOAPI_DB_PGSTAC_VERSION=0.7.1 npm --prefix infrastructure/aws run cdk -- deploy eoAPI-${CDK_EOAPI_STAGE}` returns `No stacks match the name(s) eoAPI-staging`
* I guess `CDK_EOAPI_DB_PGSTAC_VERSION` should become equal to `0.7.10`

#### Expected Output
Deploy `eoAPI` in aws.

#### Environment Information
* Os: Ununtu
* Python: 3.10.11
* Node: v18.16.1
* npm: 9.5.1
* CDK version: 2.76.0

**Comment by vincentsarago** [comment]
@charalamm thanks for opening the issue and also a PR 🙏 

when writing the documentation I assumed we could have the env variable provided in a onliner
```bash
CDK_EOAPI_STAGE=staging echo ${CDK_EOAPI_STAGE}
>> 
```

But as shown in ☝️ , it doesn't work 🤦 so to fix this you need to do 👇 
```bash
CDK_EOAPI_STAGE=staging CDK_EOAPI_DB_PGSTAC_VERSION=0.7.1 npm --prefix infrastructure/aws run cdk -- deploy eoAPI-staging
```

For the `bootstrap` part, I'm not sure what's going on but I'll have a look

**Comment by charalamm** [comment]
@vincentsarago It works now with the changes in `infrastructure/aws`. Thank you!

**Comment by charalamm** [comment]
Noted. Thanks!
