### ISSUE TITLE
Add queryables endpoint

### ISSUE THREAD

**Issue by zacharyDez** [developmentseed/eoAPI#112]
From a conversation with @developmentseed/atlantis-pod , the idea of a queryable endpoint was proposed. This feature would greatly enhance our user's ability to interact with our data collections. It would enable end-users to understand what attributes they can use to query a given collection.

A similar feature has been successfully implemented in our VEDA project. It allows users to understand what kind of queries they can make. For example, it lets users know if they are able to query certain collections based on cloud cover.

To implement this feature, @sharkinsspatial outlined the following three steps (I may be missing some details, please edit directly):

- Update STAC-fastapi: The 'queryable' endpoint is a new addition to OGC Features. As such, we'll need to update our STAC-fastapi.

- Translate it into SQL in pgstac: The next step would be to translate the new 'queryable' feature into SQL queries. These queries can then be used in the Postgres database.

- Update the connector between pgstac and stac-fastapi: The final step involves updating the connector between pgstac and stac-fastapi to ensure the new 'queryable' endpoint is fully functional.

**Comment by vincentsarago** [comment]
🤔 there is already a `/collections/{collection_id}/queryables` endpoint, are you talking about something different?

https://stac.eoapi.dev/docs#/Filter%20Extension/Collection_Queryables_collections__collection_id__queryables_get

**Comment by zacharyDez** [comment]
@vincentsarago I did not even know about this 😨 

@wildintellect @emileten is there anything that would be missing from the queryables endpoint that is implemented within other projects?

**Comment by vincentsarago** [comment]
closing this for now, but feel free to re-open
