### ISSUE TITLE
pgstac migration do not work

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/eoAPI#12]
https://github.com/developmentseed/eoAPI/blob/384e35e6d2c4533a512de414612e47241074024d/deployment/handlers/db_handler.py#L80-L90

**Comment by bitner** [comment]
@vincentsarago that code there is only ever going to build a from scratch 0.3.4, for incremental upgrades, you should directly use https://github.com/stac-utils/pgstac/blob/main/pypgstac/pypgstac/migrate.py#L132 which will use incremental migrations.
