### ISSUE TITLE
TiTiler STAC viewer returns 404

### ISSUE THREAD

**Issue by drnextgis** [developmentseed/eoAPI#16]
https://user-images.githubusercontent.com/866124/132497769-df2ab162-f45f-4e0a-afdb-0bad2f9563aa.mp4

**Comment by vincentsarago** [comment]
are you using docker-compose? 
if not can you make sure to have the `TITILER_ENDPOINT` env set pointing the eoapi.raster endpoint

https://github.com/developmentseed/eoAPI/blob/master/docker-compose.yml#L29

**Comment by drnextgis** [comment]
yes, I'm using default docker-compose.yml

**Comment by vincentsarago** [comment]
the url seems weird `raster/stac/viewer`

**Comment by vincentsarago** [comment]
👍 yep, confirmed I'm not an docker expert but it seems that https://github.com/developmentseed/eoAPI/blob/master/docker-compose.yml#L29 pass the word `raster` instead of `http://0.0.0.0:8082` 🤷

**Comment by drnextgis** [comment]
Correct, `raster` is the name which is used to communicate between containers and it is not available from the docker host. As you mentioned using `http://0.0.0.0:8082` solves the issue:
![image](https://user-images.githubusercontent.com/866124/132522712-dffe0593-b685-4702-92fa-f483528ba837.png)

**Comment by vincentsarago** [comment]
I've hardcoded the host in the docker-compose file https://github.com/developmentseed/eoAPI/blob/master/docker-compose.yml#L34
