### ISSUE TITLE
Context STAC extension

### ISSUE THREAD

**Issue by drnextgis** [developmentseed/eoAPI#32]
Context extension (to be more precise its `matched` property) is [disabled](https://github.com/stac-utils/pgstac#pgstac-settings) by default in PGStac. I think we should find a way to make it configurable.

It seems that it can be easily added to [db_handler](https://github.com/developmentseed/eoAPI/blob/master/deployment/handlers/db_handler.py) but what about [database](https://github.com/developmentseed/eoAPI/blob/893d6f52455f2311aaf103897c5387d1fbb5d917/docker-compose.yml#L155) service in the docker-compose?

**Comment by vincentsarago** [comment]
👍 

if we do want it in the docker-compose, it means we will have to create a Dockerfile, I think it's fine to not have it for now.🤷 

Feel free to update `db_handler` to register the context settings. You could either use an environment variable or pass something in the resource properties: https://github.com/developmentseed/eoAPI/blob/66085ac249752c6ef0adbb09026f187fe21f29f6/deployment/cdk/app.py#L92-L98
https://github.com/developmentseed/eoAPI/blob/66085ac249752c6ef0adbb09026f187fe21f29f6/deployment/handlers/db_handler.py#L140
