### ISSUE TITLE
Add more deployment options

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/eoAPI#63]
Let's try to have this repo less AWS oriented.

**Comment by charalamm** [comment]
Hello again, I am trying to deploy eoAPI in azure.

Currently, I am working in [this forked branch](https://github.com/charalamm/eoAPI/tree/infrastructure-azure) (which is currently pretty dirty. Sorry in advance).
I managed to deploy the database with the correct schema and to add some sample data using [this code](https://github.com/stac-utils/pgstac/issues/190).
As a next step I am trying to covert the raster API as an azure serverless function but  I have [this problem](https://github.com/Azure/azure-functions-python-worker/issues/1273) with the azure-functions - starlette cooperation. Is it something you have encountered maybe?

**Comment by vincentsarago** [comment]
We've started to look at Azure function for the planetary computer over https://github.com/microsoft/planetary-computer-apis/pull/47 maybe it can be of help

**Comment by vincentsarago** [comment]
also FYI, we're planing to remove `infrastructure` code from this repo to rely on other `official` eoapi infrastructure (eoapi-cdk and [k8s-eoapi](https://github.com/developmentseed/k8s-eoapi)) 

ref #94

**Comment by charalamm** [comment]
Seems like there is a bug in the azure functions side that makes the starlette `app.state.dbpool` throw errors:
[https://github.com/Azure/azure-functions-python-worker/issues/1273#issuecomment-1612723497](https://github.com/Azure/azure-functions-python-worker/issues/1273#issuecomment-1612723497)

**Comment by zacharyDez** [comment]
@vincentsarago @batpad; are we set to close this one?

**Comment by vincentsarago** [comment]
@zacharyDez 👍
