### ISSUE TITLE
Add stac ingestor service

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/eoAPI#65]

**Comment by emileten** [comment]
Don't we already have a [stac-ingestor in eoapi-cdk](https://github.com/developmentseed/eoapi-cdk/tree/main/lib/ingestor-api) @vincentsarago ?

**Comment by zacharyDez** [comment]
I think the idea would be to have an endpoint where users can make a post request to @emileten . The underlying details need to be worked out.

**Comment by sharkinsspatial** [comment]
@zacharyDez Users do make a `POST` request using the [eoapi-cdk STAC Ingestor API](https://github.com/developmentseed/eoapi-cdk#stac-ingestor).  

I think we might want to close this issue in favor of the path outlined in https://github.com/developmentseed/eoAPI/issues/94 and open a new issue for implementing the [transaction extension](https://stac-utils.github.io/stac-fastapi/api/stac_fastapi/extensions/core/transaction/) that can be used directly in local and k8s deployments.  As well as open a new issue showing how to use the STAC Ingestor API when working with the cdk deployment.

**Comment by emileten** [comment]
So I think the only TODO in this ticket was to _actually_ add this ingestor service in our demo deployment, which I did : `https://ingestor.eoapi.dev/`. This will show 'Not found', it's normal. Sorry the /docs endpoint is broken. 

I'll fix the docs endpoint, but the gist is that you can make a post request to either the `collections` or the `ingestions` endpoint to add a collection/item to your catalog. 

I'll close this for now. 

- there is already a ticket to fix the docs https://github.com/developmentseed/eoapi-cdk/issues/79
- there is work in progress to have a standalone repo for this ingestor (we should add docs there)  https://github.com/developmentseed/pgstac-ingestor
